In [1]:
import pandas as pd
import numpy as np
import igraph as ig
import leidenalg
import math
import networkx as nx
from collections import defaultdict
import os
from scipy.stats import false_discovery_control

In [2]:
#Load and preprocess GRN 
raw_grn = pd.read_csv("/home/quantori/Downloads/data/joung/raw_GRN_for_ehgc.csv")

In [3]:
raw_grn

,Unnamed: 0,source,target,coef_mean,coef_abs,p,-logp
0,0,CREB3L3,A1CF,0.000144,0.000144,2.846976e-05,4.545616
1,1,PRDM1,A1CF,0.000286,0.000286,3.975981e-11,10.400556
2,2,AIRE,A1CF,0.000089,0.000089,1.731293e-06,5.761629
3,3,FOXA2,A3GALT2,0.000330,0.000330,4.504073e-11,10.346395
4,4,FERD3L,A3GALT2,0.000253,0.000253,2.934097e-07,6.532526
...,...,...,...,...,...,...,...
11704,11704,BCL11A,ZNF99,0.000029,0.000029,3.002626e-04,3.522499
11705,11705,MEF2C,ZNF99,-0.000019,0.000019,4.674537e-02,1.330261
11706,11706,LHX1,ZNF99,-0.000065,0.000065,1.396086e-05,4.855088
11707,11707,AIRE,ZNF99,-0.000124,0.000124,3.854296e-10,9.414055
11708,11708,ESR1,ZNF99,-0.000039,0.000039,4.978273e-03,2.302921

In [4]:
len(set(raw_grn["source"]).union(set(raw_grn["target"])))

1171

In [5]:
#Drop NA or 0 values in P column
raw_grn = raw_grn.dropna(subset=["p"])

In [6]:
raw_grn

,Unnamed: 0,source,target,coef_mean,coef_abs,p,-logp
0,0,CREB3L3,A1CF,0.000144,0.000144,2.846976e-05,4.545616
1,1,PRDM1,A1CF,0.000286,0.000286,3.975981e-11,10.400556
2,2,AIRE,A1CF,0.000089,0.000089,1.731293e-06,5.761629
3,3,FOXA2,A3GALT2,0.000330,0.000330,4.504073e-11,10.346395
4,4,FERD3L,A3GALT2,0.000253,0.000253,2.934097e-07,6.532526
...,...,...,...,...,...,...,...
11704,11704,BCL11A,ZNF99,0.000029,0.000029,3.002626e-04,3.522499
11705,11705,MEF2C,ZNF99,-0.000019,0.000019,4.674537e-02,1.330261
11706,11706,LHX1,ZNF99,-0.000065,0.000065,1.396086e-05,4.855088
11707,11707,AIRE,ZNF99,-0.000124,0.000124,3.854296e-10,9.414055
11708,11708,ESR1,ZNF99,-0.000039,0.000039,4.978273e-03,2.302921

In [7]:
#FDR filtering and only leaving P values less than 0.05

adjusted_pvals = false_discovery_control(raw_grn['p'].values, method='bh')

In [8]:
raw_grn['p'] = adjusted_pvals

In [9]:
raw_grn

,Unnamed: 0,source,target,coef_mean,coef_abs,p,-logp
0,0,CREB3L3,A1CF,0.000144,0.000144,4.236812e-05,4.545616
1,1,PRDM1,A1CF,0.000286,0.000286,1.861446e-10,10.400556
2,2,AIRE,A1CF,0.000089,0.000089,3.001437e-06,5.761629
3,3,FOXA2,A3GALT2,0.000330,0.000330,2.074673e-10,10.346395
4,4,FERD3L,A3GALT2,0.000253,0.000253,5.691740e-07,6.532526
...,...,...,...,...,...,...,...
11704,11704,BCL11A,ZNF99,0.000029,0.000029,4.028157e-04,3.522499
11705,11705,MEF2C,ZNF99,-0.000019,0.000019,5.281180e-02,1.330261
11706,11706,LHX1,ZNF99,-0.000065,0.000065,2.148347e-05,4.855088
11707,11707,AIRE,ZNF99,-0.000124,0.000124,1.361797e-09,9.414055
11708,11708,ESR1,ZNF99,-0.000039,0.000039,6.037974e-03,2.302921

In [10]:
filtered_grn = raw_grn[raw_grn['p'] <= 0.05]

In [11]:
filtered_grn

,Unnamed: 0,source,target,coef_mean,coef_abs,p,-logp
0,0,CREB3L3,A1CF,0.000144,0.000144,4.236812e-05,4.545616
1,1,PRDM1,A1CF,0.000286,0.000286,1.861446e-10,10.400556
2,2,AIRE,A1CF,0.000089,0.000089,3.001437e-06,5.761629
3,3,FOXA2,A3GALT2,0.000330,0.000330,2.074673e-10,10.346395
4,4,FERD3L,A3GALT2,0.000253,0.000253,5.691740e-07,6.532526
...,...,...,...,...,...,...,...
11703,11703,PAX5,ZNF99,0.000055,0.000055,3.838758e-07,6.714730
11704,11704,BCL11A,ZNF99,0.000029,0.000029,4.028157e-04,3.522499
11706,11706,LHX1,ZNF99,-0.000065,0.000065,2.148347e-05,4.855088
11707,11707,AIRE,ZNF99,-0.000124,0.000124,1.361797e-09,9.414055
11708,11708,ESR1,ZNF99,-0.000039,0.000039,6.037974e-03,2.302921

In [12]:
len(set(filtered_grn["source"]).union(set(filtered_grn["target"])))

1170

In [ ]:
# Load TF reference
tf_info = pd.read_parquet("hg38_TFinfo_dataframe_gimmemotifsv5_fpr2_threshold_10_20210630.parquet")  ## Google Drive: gCAL_data > Joung2013_results

In [14]:
tf_info

,peak_id,gene_short_name,9430076C15RIK,AC002126.6,AC012531.1,AC226150.2,AFP,AHR,AHRR,AIRE,...,ZNF784,ZNF8,ZNF816,ZNF85,ZSCAN10,ZSCAN16,ZSCAN22,ZSCAN26,ZSCAN31,ZSCAN4
0,chr10_100009853_100010953,DNMBP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,chr10_100081785_100082885,CPN1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,chr10_100185877_100186977,ERLIN1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,chr10_100186978_100187057,ERLIN1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,chr10_100229510_100230610,CHUK,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39310,chrY_9721196_9722296,TTTY21B,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39311,chrY_9735286_9736386,TTTY2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
39312,chrY_9774219_9775319,TTTY1B,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39313,chrY_9800153_9801253,TTTY22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39314,chrY_9909798_9910898,TTTY23B,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [15]:
tf_names = set(tf_info.columns.unique())

In [16]:
tf_names

{'CR925796.2',
 'ZFP28',
 'GRHL2',
 'NR2E3',
 'FOXE3',
 'JDP2',
 'CEBPE',
 'SIX1',
 'TCF3',
 'TCF7',
 'NFKB2',
 'ZFP784',
 'ZNF770',
 'GZF1',
 'SP6',
 'TFEC',
 'ZBTB7B',
 'ZFP957',
 'GFI1B',
 'SREBF1',
 'HOXC5',
 'HESX1',
 'EGR3',
 'RFX8',
 'BCL6B',
 'SP2',
 'E2F5',
 'GATA1',
 'IRF2',
 'KLF13',
 'TBX5',
 'ELF3',
 'OTX2',
 'TFDP1',
 'OBOX1',
 'TEAD2',
 'FOXA',
 'ENSG00000237516',
 'MYF',
 'HOXD1',
 'CDX2',
 'SNAI2',
 'TFE3',
 'FOXJ1',
 'ENO1',
 'ZNF628',
 'NKX3.1',
 'SOX14',
 'DBP',
 'FOXO6',
 'BARX1',
 'ZNF691',
 'MAFK',
 'TBX20',
 'ISL1',
 'ELK4',
 'MYOD1',
 'SOX10',
 'RFX7',
 'ZFP187',
 'TCFEB',
 'AP1',
 'TBP',
 'HOXC13',
 'CMYC',
 'GLI2',
 'ONECUT1',
 'ZNF740',
 'ZSCAN10',
 'FOXP3',
 'SFPI1',
 'ZEB1',
 'ZNF238',
 'E2F2',
 'HOXB4',
 'SOX4',
 'GM239',
 'KLF16',
 'PITX3',
 'ZIC5',
 'BMYB',
 'SMARCA1',
 'TLX3',
 'ZNF816',
 'ZKSCAN1',
 'PAX1',
 'BHLHE41',
 'HOXB9',
 'ETV5',
 'ENSMUSG00000079994',
 'CREB1',
 'FOXO3',
 'HMX2',
 'LHX4',
 'NKX2-5',
 'GBX2',
 'ZFP523',
 'FOXD1',
 'GRE',
 'MEF2B',
 'ZNF713',
 'SMARCC1',
 'FOXP2',
 'HEY1',
 'SIX2',
 'ENSG00000233361',
 'ENSG00000250589',
 'NFY',
 'POU2F2',
 'CPHX',
 'ZNF768',
 'SPIB',
 'IRF3',
 'PLAGL1',
 'PTEN',
 'ZNF257',
 'ZNF75D',
 'ETV4',
 'FOXQ1',
 'RREB1',
 'ZNF784',
 'MNT',
 'ZNF136',
 'ZNF121',
 'RXRB',
 'EBNA1',
 'HNF4G',
 'CREB3L3',
 'TCFCP2',
 'ENSMUSG00000090020',
 '9430076C15RIK',
 'ZFP128',
 'LEF1',
 'PURA',
 'ZFP282',
 'ENSG00000233698',
 'NKX2-1',
 'PGR',
 'FOXN1',
 'SIX3',
 'CENPB',
 'ELF2',
 'ETS1',
 'ZFP143',
 'AL844527.7',
 'LMX1A',
 'GATA5',
 'TP63',
 'ZIM3',
 'FOXD3',
 'OTP',
 'ZNF331',
 'ZNF274',
 'KLF8',
 'ENSMUSG00000040953',
 'RFX6',
 'BCL6',
 'CCDC6',
 'CSDA',
 'MLX',
 'NR4A3',
 'LMX1B',
 'PU.1',
 'ZFX',
 'NOBOX',
 'POU5F1P1',
 'GABPA',
 'PBX4',
 'MEIS2',
 'SP4',
 'SIN3A',
 'ZBTB12',
 'POU2F1',
 'ZFP263',
 'UNCX',
 'ZNF350',
 'PITX1',
 'ZNF260',
 'ATOH8',
 'BX284686.1',
 'FOXJ3',
 'DMRTB1',
 'ENSG00000187728',
 'HNF4',
 'IRX5',
 'ZFA',
 'HOXA5',
 'FLI1',
 'SOX17',
 'ZNF652',
 'NEUROD4',
 'CBX5',
 'RELA',
 'ZNF282',
 'ZSCAN22',
 'TCFAP2A',
 'UBP1',
 'EOMES',
 'ZNF667',
 'OBOX2',
 'ATF7',
 'NFYA',
 'ENSG00000217642',
 'HES1',
 'CREB3L2',
 'SCRT2',
 'MYCN',
 'ERRA',
 'HOXB7',
 'BX088580.2',
 'FOXD4L1',
 'NPAS3',
 'NFIC',
 'TCF15',
 'GLIS2',
 'MLXIPL',
 'HSFY2',
 'ALX3',
 'HLTF',
 'IRX4',
 'MYC',
 'NR1D2',
 'EGR1',
 'PATZ1',
 'SOX11',
 'RXR',
 'PPARD',
 'SOX21',
 'DBX2',
 'FOXF1',
 'ENSG00000215754',
 'INSM1',
 'FOXN3',
 'SMAD4',
 'DRGX',
 'ENSG00000226866',
 'NHLH1',
 'SOX15',
 'ZNF85',
 'BACH1',
 'NKX2-4',
 'HOXB13',
 'HIC1',
 'TBX21',
 'VSX2',
 'BHLHA15',
 'NKX6-1',
 'TLX1',
 'ZNF341',
 'ENSG00000230380',
 'OCT2',
 'CBFB',
 'POLR3G',
 'ZNF586',
 'E2F6',
 'ARNTL',
 'ARID3A',
 'FOXP1',
 'KLF14',
 'MSX2',
 'RFX1',
 'CRX',
 'PAX',
 'ENSG00000232923',
 'EZH2',
 'POU3F3',
 'PPARGC1A',
 'RORC',
 'FOXD2',
 'LHX6',
 'DUX4L6',
 'MSGN1',
 'PRDM1',
 'TFCP2',
 'RHOXF1',
 'DUX4L5',
 'TAL1',
 'ARID5A',
 'STAT5B',
 'SREBP1A',
 'GRHL1',
 'HMGA1',
 'NR1D1',
 'SNAI1',
 'ZNF8',
 'ZNF306',
 'IRF7',
 'EP300',
 'ALX4',
 'NKX2.2',
 'NKX2-8',
 'CDX4',
 'HOXD12',
 'OVOL1',
 'TCF12',
 'FOS',
 'PBX',
 'HMGN3',
 'HOXD10',
 'CEBPZ',
 'TEAD4',
 'ZNF214',
 'TERF2',
 'ENSG00000250542',
 'FOXE1',
 'NP_663755.2',
 'TBX22',
 'ARID5B',
 'HNF4A',
 'CR759733.4',
 'CACBP',
 'ETS2',
 'HDX',
 'TCFE3',
 'ENSG00000250096',
 'RDBP',
 'MYBL2',
 'VAX1',
 'ZNF140',
 'USF2',
 'BX927239.6',
 'POU5F1',
 'SPZ1',
 'FOXN2',
 'ZFP652',
 'CREB5',
 'ZNF146',
 'ETV2',
 'ZBED1',
 'ATF6',
 'PBX1',
 'CREM',
 'HOXD13',
 'ATF3',
 'AC226150.2',
 'IRF4',
 'NMYC',
 'NR1A4',
 'MTF1',
 'COMP1',
 'ZBTB4',
 'FOXF2',
 'PITX2',
 'TFAP2A',
 'TRP73',
 'DUXA',
 'HOXA4',
 'LHX8',
 'HOXA7',
 'HSF4',
 'ZNF528',
 'ENSMUSG00000044690',
 'NFIA',
 'TFAP2E',
 'XBP1',
 'MAFB',
 'HOXC11',
 'SCRT1',
 'MYOG',
 'SMARCB1',
 'ASCL2',
 'DUX4L3',
 'ALX1',
 'POU',
 'ATF5',
 'TAF1',
 'FUBP1',
 'FOXA1',
 'NKX2.5',
 'SPIC',
 'BATF',
 'MAFA',
 'ZFP105',
 'TBX3',
 'BCL11A',
 'NFATC3',
 'SHOX2',
 'ZBTB33',
 'GMEB2',
 'JUN',
 'ENSG00000236207',
 'FERD3L',
 'KLF15',
 'NEUROD2',
 'SMARCA5',
 'ZFP42',
 'BRN2',
 'FOXL1',
 'TFDP2',
 'ZBTB18',
 'LBX1',
 'MYCL1',
 'SP5',
 'BRACHYURY',
 'NR5A1',
 'HOXA2',
 'LHX9',
 'OVOL2',
 'OSR1',
 'ENSG00000250811',
 'gene_short_name',
 'BARHL1',
 'NP_032296.2',
 'ENSG00000230776',
 'CDC5L',
 'ATOH7',
 'DDIT3',
 'GABP',
 'MAX',
 'ZFP740',
 'HAND1',
 'IKZF4',
 'ZNF264',
 'ZSCAN31',
 'IRF8',
 'PKNOX1',
 'CR759815.4',
 'RUNX1',
 'EGR4',
 'ZNF502',
 'ETV1',
 'ESRRB',
 'CTCF',
 'ZFY',
 'NR1H2',
 'PRDM9',
 'MEIS3',
 'HSF1',
 'MYBL1',
 'ENSG00000233294',
 'NR2F6',
 'GLI',
 'ZFP110',
 'AL662833.4',
 'NR4A1',
 'NFE2',
 'TFE',
 'ARNT',
 'HOXC12',
 'MEIS1',
 'RFX4',
 'ZSCAN26',
 'KLF11',
 'REL',
 'ZNF554',
 'ZNF75A',
 'ZNF322',
 'FOXF1A',
 'BDP1',
 'NFE2L1',
 'RBPSUH-RS3',
 'ZIC3',
 'ERF',
 'SOX13',
 'NR4A2',
 'ZFP57',
 'ZFHX3',
 'NR1H',
 'BATF3',
 'TCFAP2B',
 'NKX3-2',
 'NFATC1',
 'POU3F1',
 'KLF6',
 'NPAS4',
 'TBX4',
 'AP3',
 'IRX6',
 'SOX7',
 'PRRXL1',
 'ZFP82',
 'ZNF418',
 'CR936877.3',
 'HERPUD1',
 'HOXA9',
 'TRP53',
 'ZBTB47',
 'YY1',
 'FXR',
 'ZFP691',
 'MLXIP',
 'HOXC8',
 'DUX4L2',
 'TCFCP2L1',
 'CREB',
 'MYPOP',
 'BCL11B',
 'MSC',
 'FOXI3',
 'MEF2D',
 'RARG',
 'USF',
 'FOXD4L3',
 'FOXD4',
 'RFX5',
 'TRP63',
 'POU4F1',
 'ZFP524',
 'AHRR',
 'HOXD8',
 'ARID3C',
 'PTF1A',
 'SMARCC2',
 'LBX2',
 'ESR1',
 'AIRE',
 'ETV3',
 'RORB',
 'ZNF165',
 'GTF3C2',
 'DLX2',
 'IKZF3',
 'KLF4',
 'NANOG',
 'NR2F2',
 'SIX6',
 'TEAD3',
 'CART1',
 'BSX',
 'NHLH2',
 'TP53',
 'EN2',
 'HOXA10',
 'GFI1',
 'ZNF490',
 'POU4F2',
 'MBTPS2',
 'STAT1',
 'AR',
 'C11ORF9',
 'HOXD11',
 'CR812478.2',
 'NR3C1',
 'SALL4',
 'CEBPA',
 'DMRTC2',
 'NKX3-1',
 'HOMEZ',
 'SP3',
 'CHD2',
 'DMRTA1',
 'FOXA3',
 'ZNF263',
 'Q8VHG7_MOUSE',
 'GTF2I',
 'MYF6',
 'RHOX8',
 'SREBF2',
 'TCFAP4',
 'JUND',
 'ZBTB14',
 'ENSG00000224558',
 'THRA',
 'PR',
 'NP_001076596.1',
 'SIX4',
 'NR5A2',
 'FOSL2',
 'TBX19',
 'NFIB',
 'AL662834.13',
 'RXRA',
 'EHF',
 'STAT5',
 'HF1H3B',
 'HOXA1',
 'CXXC1',
 'BRF1',
 'FOX',
 'MEF2A',
 'OTX',
 'TFAP2',
 'USF1',
 'NR1I3',
 'HOXD3',
 'NKX2-6',
 'FOXS1',
 'MZF1',
 'CREB3L4',
 'ZNF232',
 'FEV',
 'ZNF35',
 'ENSG00000234550',
 'HES2',
 'PRDM5',
 'ARID3B',
 'NP_083278.1',
 'HOXD9',
 'RBPJ',
 'NKX2.1',
 'STAT',
 'SOX8',
 'NANOGP1',
 'RFX3',
 'RELB',
 'TGIF2',
 'ARHGEF12',
 'TGIF2LX',
 'ZNF219',
 'CREBZF',
 'DUX4',
 'FOXD4L5',
 'ESR2',
 'BHLHE40',
 'HAND2',
 'MYB',
 'NFAT',
 'ZIC1',
 'ZNF708',
 'HMGA2',
 'PAX3',
 'PRDM14',
 'NKX2-2',
 'TBX10',
 'ZNF449',
 'LHX1',
 'GATA',
 'BBX',
 'CR388219.4',
 'HES7',
 'TEAD1',
 'BACH2',
 'ONECUT2',
 'SMAD3',
 'FOXI2',
 'ZFP369',
 'DMBX1',
 'NF1',
 'CTCFL',
 'BHLHB3',
 'ENSG00000234254',
 'ELF5',
 'ID3',
 'NP_032300.2',
 'OBOX3',
 'SMAD1',
 'STAT6',
 'SCX',
 'THAP1',
 'CEBP',
 'HES5',
 'IRF',
 'FOSL1',
 'HMGA1-RS1',
 'TCFAP2C',
 'SREBP2',
 'FOXK1',
 'GSC2',
 'ZNF143',
 'ESRRA',
 'HDAC2',
 'GCM1',
 'POU1F1',
 'FEZF1',
 'IRX3',
 'FOXB2',
 'BMAL1',
 'POLR3A',
 'FOSB',
 'LYL1',
 'EGR2',
 'SNAI3',
 'TCFAP2E',
 'HEYL',
 'ZFP219',
 'RFX2',
 'NR0B1',
 'SOX18',
 'TFAP2B',
 'WT1',
 'NR6A1',
 'CUX2',
 'HOXB6',
 'FOXD4L6',
 'SEF1',
 'ZNF281',
 'DLX5',
 'SP7',
 'AL844853.8',
 'PROX1',
 'DMRT1',
 'E2F7',
 'EGR',
 'NPAS1',
 'EMX1',
 'KLF10',
 'PAX4',
 'BARX2',
 'BPTF',
 'CCNT2',
 'MECOM',
 'ZNF435',
 'GM5454',
 'ATOH1',
 'ZNF549',
 'MBD2',
 'KLF3',
 'SOX6',
 'HOXC9',
 'NEUROG1',
 'VENTX',
 'HOXA11',
 'MYF5',
 'ZBTB1',
 'FOXK2',
 'AL773544.1',
 'PRRX2',
 'NEUROG3',
 'NFYC',
 'PRDM4',
 'EBF3',
 'NEUROD1',
 'PAX2',
 'AL592170.2',
 'HNF1B',
 'SMAD2',
 'TCFL5',
 'ESRRG',
 'YBX1',
 'ZNF335',
 'TBX15',
 'ZBTB6',
 'EN1',
 'TOPORS',
 'LHX5',
 'ZKSCAN3',
 'CEBPG',
 'EBF1',
 'MAZ',
 'DOBOX4',
 'TBX2',
 'ZNF148',
 'ZNF582',
 'SOX9',
 'TWIST2',
 'BHLHE23',
 'PBX2',
 'TCF7L1',
 'CR933878.8',
 'TFCP2L1',
 'AL662824.5',
 'DMRT2',
 'DMC1',
 'POU3F2',
 'RORA',
 'ZSCAN16',
 'NEUROD6',
 'FOXP4',
 'PAX7',
 'AC002126.6',
 'CR753803.1',
 'ZNF547',
 'TFDP3',
 'ZBTB42',
 'WRNIP1',
 'NFATC2',
 'TBET',
 'HOXB5',
 'GATA3',
 'OBOX6',
 'DUX',
 'SIM2',
 'MECP2',
 'SRY',
 'E2F4',
 'ZNF41',
 'PRDM16',
 'PBX3',
 'REST',
 'GLIS1',
 'P63',
 'ZNF324',
 'ENSG00000235187',
 'HIF1A',
 'PPARG',
 'BRCA1',
 'NFATC4',
 'POU5F1B',
 'NR1H5',
 'MBD1',
 'RAX',
 'NRL',
 'FOXB1',
 'TCF7L2',
 'SPI1',
 'CT476828.2',
 'IRF1',
 'NR3C2',
 'RUNX3',
 'ZNF589',
 'TGIF1',
 'SIM1',
 'MXI1',
 'PPARA',
 'SIRT6',
 'ZBTB49',
 'ELK1',
 'ZBTB17',
 'HINFP1',
 'ETV7',
 'ARNTL2',
 'DLX1',
 'MEOX1',
 'VSX1',
 'FOXC2',
 'ZNF680',
 'TR4',
 'STAT3',
 'GATA2',
 'MITF',
 'DPRX',
 'NR2F1',
 'NRF1',
 'ZNF18',
 'CUX1',
 'HOXB8',
 'KLF1',
 'CR388229.2',
 'NFIX',
 'TCFEC',
 'DMRTA2',
 'ELK3',
 'IRF9',
 'HIC2',
 'MGA',
 'NR2E1',
 'SP8',
 'TCF4',
 'TGIF2LY',
 'HIVEP2',
 'BCLAF1',
 'FEZF2',
 'OLIG2',
 'ENSG00000233794',
 'POU6F2',
 'RXRG',
 'CDX',
 'HNF1',
 'ATF2',
 'E4F1',
 'AL662828.6',
 'NEUROG2',
 'GLIS3',
 'IRF6',
 'SP1',
 'ZFP3',
 'MYEF2',
 'ZNF423',
 'KLF9',
 'FOXJ2',
 'ZFP238',
 'NR2C2',
 'RHOXF2',
 'POU2F3',
 'ID1',
 'STAT4',
 'MAF',
 'HMX1',
 'NKX6-2',
 'ZFP410',
 'POU3F4',
 'GTF2A',
 'DMRT3',
 'EBF',
 'NR2C1',
 'NFKB',
 'MAFF',
 'ZKSCAN4',
 'PIT1',
 'AL662830.5',
 'KLF7',
 'KLF2',
 'CEBPD',
 'GCM',
 'HLX',
 'ZBTB7A',
 'SRF',
 'IRX2',
 'HBP1',
 'FOXI1',
 'NR1H4',
 'ZBTB48',
 'ZNF563',
 'ONECUT3',
 'HIVEP1',
 'GSC',
 'SOX',
 'VEZF1',
 'NKX2-3',
 'TBR1',
 'OCT4',
 'GATA4',
 'ISL2',
 'LHX2',
 'FOXO4',
 'FRA2',
 'HOXB2',
 'SREBF',
 'BRN1',
 'HOXD4',
 'ZNF320',
 'IRC900814',
 'HSF2',
 'ELF4',
 'IKZF1',
 'BHLHB2',
 'NP_032283.3',
 'BARHL2',
 'PAX8',
 'CLOCK',
 'FOXC1',
 'SOX2',
 'AMYB',
 'AFP',
 'EBOX',
 'ZFP281',
 'ARNT2',
 'ATF1',
 'HSFY1',
 'HLF',
 'NPAS',
 'EMX2',
 'HOXA6',
 'ESX1',
 'POU6F1',
 'E2F1',
 'ATF4',
 'ENSG00000227522',
 'SCXB',
 'DBX1',
 'YBX2',
 'SPDEF',
 'SP9',
 'ERG',
 'ZNF329',
 'RUNX2',
 'peak_id',
 'ZNF394',
 'GSX1',
 'MEOX2',
 'TCF23',
 'KLF5',
 'FOXL2',
 'OSR2',
 'FOXM1',
 'OLIG1',
 'SP100',
 'ZFY1',
 'ZNF354A',
 'PHF21A',
 'RHOX11',
 'ZSCAN4',
 'TBX18',
 'GCM2',
 'NFYB',
 'ARX',
 'ATF6B',
 'DMRT6',
 'NRF2',
 'ZNF524',
 'ZBTB7C',
 'ZFP161',
 'POLR2A',
 'ZFP809',
 'RAD21',
 'NFKB1',
 'ZNF76',
 'CEBPB',
 'OTX1',
 'TEF',
 'IRF5',
 'GLI1',
 'MSX1',
 'PAX6',
 'TCF21',
 'NPAS2',
 'SCXA',
 'ASCL1',
 'HOXC6',
 'OLIG3',
 'LMO2',
 'TFAP4',
 'HMX3',
 'PHOX2A',
 'ZNF683',
 'PROP1',
 'CACD',
 'BRF2',
 'ZIC4',
 'AL845464.3',
 'ETV6',
 'ITGB2',
 'TCFAP2D',
 'EWSR1',
 'YY2',
 'ZNF382',
 'FOXH1',
 'SETDB1',
 'GSX2',
 'MEF2C',
 ...}

In [17]:
tf_names

{'CR925796.2',
 'ZFP28',
 'GRHL2',
 'NR2E3',
 'FOXE3',
 'JDP2',
 'CEBPE',
 'SIX1',
 'TCF3',
 'TCF7',
 'NFKB2',
 'ZFP784',
 'ZNF770',
 'GZF1',
 'SP6',
 'TFEC',
 'ZBTB7B',
 'ZFP957',
 'GFI1B',
 'SREBF1',
 'HOXC5',
 'HESX1',
 'EGR3',
 'RFX8',
 'BCL6B',
 'SP2',
 'E2F5',
 'GATA1',
 'IRF2',
 'KLF13',
 'TBX5',
 'ELF3',
 'OTX2',
 'TFDP1',
 'OBOX1',
 'TEAD2',
 'FOXA',
 'ENSG00000237516',
 'MYF',
 'HOXD1',
 'CDX2',
 'SNAI2',
 'TFE3',
 'FOXJ1',
 'ENO1',
 'ZNF628',
 'NKX3.1',
 'SOX14',
 'DBP',
 'FOXO6',
 'BARX1',
 'ZNF691',
 'MAFK',
 'TBX20',
 'ISL1',
 'ELK4',
 'MYOD1',
 'SOX10',
 'RFX7',
 'ZFP187',
 'TCFEB',
 'AP1',
 'TBP',
 'HOXC13',
 'CMYC',
 'GLI2',
 'ONECUT1',
 'ZNF740',
 'ZSCAN10',
 'FOXP3',
 'SFPI1',
 'ZEB1',
 'ZNF238',
 'E2F2',
 'HOXB4',
 'SOX4',
 'GM239',
 'KLF16',
 'PITX3',
 'ZIC5',
 'BMYB',
 'SMARCA1',
 'TLX3',
 'ZNF816',
 'ZKSCAN1',
 'PAX1',
 'BHLHE41',
 'HOXB9',
 'ETV5',
 'ENSMUSG00000079994',
 'CREB1',
 'FOXO3',
 'HMX2',
 'LHX4',
 'NKX2-5',
 'GBX2',
 'ZFP523',
 'FOXD1',
 'GRE',
 'MEF2B',
 'ZNF713',
 'SMARCC1',
 'FOXP2',
 'HEY1',
 'SIX2',
 'ENSG00000233361',
 'ENSG00000250589',
 'NFY',
 'POU2F2',
 'CPHX',
 'ZNF768',
 'SPIB',
 'IRF3',
 'PLAGL1',
 'PTEN',
 'ZNF257',
 'ZNF75D',
 'ETV4',
 'FOXQ1',
 'RREB1',
 'ZNF784',
 'MNT',
 'ZNF136',
 'ZNF121',
 'RXRB',
 'EBNA1',
 'HNF4G',
 'CREB3L3',
 'TCFCP2',
 'ENSMUSG00000090020',
 '9430076C15RIK',
 'ZFP128',
 'LEF1',
 'PURA',
 'ZFP282',
 'ENSG00000233698',
 'NKX2-1',
 'PGR',
 'FOXN1',
 'SIX3',
 'CENPB',
 'ELF2',
 'ETS1',
 'ZFP143',
 'AL844527.7',
 'LMX1A',
 'GATA5',
 'TP63',
 'ZIM3',
 'FOXD3',
 'OTP',
 'ZNF331',
 'ZNF274',
 'KLF8',
 'ENSMUSG00000040953',
 'RFX6',
 'BCL6',
 'CCDC6',
 'CSDA',
 'MLX',
 'NR4A3',
 'LMX1B',
 'PU.1',
 'ZFX',
 'NOBOX',
 'POU5F1P1',
 'GABPA',
 'PBX4',
 'MEIS2',
 'SP4',
 'SIN3A',
 'ZBTB12',
 'POU2F1',
 'ZFP263',
 'UNCX',
 'ZNF350',
 'PITX1',
 'ZNF260',
 'ATOH8',
 'BX284686.1',
 'FOXJ3',
 'DMRTB1',
 'ENSG00000187728',
 'HNF4',
 'IRX5',
 'ZFA',
 'HOXA5',
 'FLI1',
 'SOX17',
 'ZNF652',
 'NEUROD4',
 'CBX5',
 'RELA',
 'ZNF282',
 'ZSCAN22',
 'TCFAP2A',
 'UBP1',
 'EOMES',
 'ZNF667',
 'OBOX2',
 'ATF7',
 'NFYA',
 'ENSG00000217642',
 'HES1',
 'CREB3L2',
 'SCRT2',
 'MYCN',
 'ERRA',
 'HOXB7',
 'BX088580.2',
 'FOXD4L1',
 'NPAS3',
 'NFIC',
 'TCF15',
 'GLIS2',
 'MLXIPL',
 'HSFY2',
 'ALX3',
 'HLTF',
 'IRX4',
 'MYC',
 'NR1D2',
 'EGR1',
 'PATZ1',
 'SOX11',
 'RXR',
 'PPARD',
 'SOX21',
 'DBX2',
 'FOXF1',
 'ENSG00000215754',
 'INSM1',
 'FOXN3',
 'SMAD4',
 'DRGX',
 'ENSG00000226866',
 'NHLH1',
 'SOX15',
 'ZNF85',
 'BACH1',
 'NKX2-4',
 'HOXB13',
 'HIC1',
 'TBX21',
 'VSX2',
 'BHLHA15',
 'NKX6-1',
 'TLX1',
 'ZNF341',
 'ENSG00000230380',
 'OCT2',
 'CBFB',
 'POLR3G',
 'ZNF586',
 'E2F6',
 'ARNTL',
 'ARID3A',
 'FOXP1',
 'KLF14',
 'MSX2',
 'RFX1',
 'CRX',
 'PAX',
 'ENSG00000232923',
 'EZH2',
 'POU3F3',
 'PPARGC1A',
 'RORC',
 'FOXD2',
 'LHX6',
 'DUX4L6',
 'MSGN1',
 'PRDM1',
 'TFCP2',
 'RHOXF1',
 'DUX4L5',
 'TAL1',
 'ARID5A',
 'STAT5B',
 'SREBP1A',
 'GRHL1',
 'HMGA1',
 'NR1D1',
 'SNAI1',
 'ZNF8',
 'ZNF306',
 'IRF7',
 'EP300',
 'ALX4',
 'NKX2.2',
 'NKX2-8',
 'CDX4',
 'HOXD12',
 'OVOL1',
 'TCF12',
 'FOS',
 'PBX',
 'HMGN3',
 'HOXD10',
 'CEBPZ',
 'TEAD4',
 'ZNF214',
 'TERF2',
 'ENSG00000250542',
 'FOXE1',
 'NP_663755.2',
 'TBX22',
 'ARID5B',
 'HNF4A',
 'CR759733.4',
 'CACBP',
 'ETS2',
 'HDX',
 'TCFE3',
 'ENSG00000250096',
 'RDBP',
 'MYBL2',
 'VAX1',
 'ZNF140',
 'USF2',
 'BX927239.6',
 'POU5F1',
 'SPZ1',
 'FOXN2',
 'ZFP652',
 'CREB5',
 'ZNF146',
 'ETV2',
 'ZBED1',
 'ATF6',
 'PBX1',
 'CREM',
 'HOXD13',
 'ATF3',
 'AC226150.2',
 'IRF4',
 'NMYC',
 'NR1A4',
 'MTF1',
 'COMP1',
 'ZBTB4',
 'FOXF2',
 'PITX2',
 'TFAP2A',
 'TRP73',
 'DUXA',
 'HOXA4',
 'LHX8',
 'HOXA7',
 'HSF4',
 'ZNF528',
 'ENSMUSG00000044690',
 'NFIA',
 'TFAP2E',
 'XBP1',
 'MAFB',
 'HOXC11',
 'SCRT1',
 'MYOG',
 'SMARCB1',
 'ASCL2',
 'DUX4L3',
 'ALX1',
 'POU',
 'ATF5',
 'TAF1',
 'FUBP1',
 'FOXA1',
 'NKX2.5',
 'SPIC',
 'BATF',
 'MAFA',
 'ZFP105',
 'TBX3',
 'BCL11A',
 'NFATC3',
 'SHOX2',
 'ZBTB33',
 'GMEB2',
 'JUN',
 'ENSG00000236207',
 'FERD3L',
 'KLF15',
 'NEUROD2',
 'SMARCA5',
 'ZFP42',
 'BRN2',
 'FOXL1',
 'TFDP2',
 'ZBTB18',
 'LBX1',
 'MYCL1',
 'SP5',
 'BRACHYURY',
 'NR5A1',
 'HOXA2',
 'LHX9',
 'OVOL2',
 'OSR1',
 'ENSG00000250811',
 'gene_short_name',
 'BARHL1',
 'NP_032296.2',
 'ENSG00000230776',
 'CDC5L',
 'ATOH7',
 'DDIT3',
 'GABP',
 'MAX',
 'ZFP740',
 'HAND1',
 'IKZF4',
 'ZNF264',
 'ZSCAN31',
 'IRF8',
 'PKNOX1',
 'CR759815.4',
 'RUNX1',
 'EGR4',
 'ZNF502',
 'ETV1',
 'ESRRB',
 'CTCF',
 'ZFY',
 'NR1H2',
 'PRDM9',
 'MEIS3',
 'HSF1',
 'MYBL1',
 'ENSG00000233294',
 'NR2F6',
 'GLI',
 'ZFP110',
 'AL662833.4',
 'NR4A1',
 'NFE2',
 'TFE',
 'ARNT',
 'HOXC12',
 'MEIS1',
 'RFX4',
 'ZSCAN26',
 'KLF11',
 'REL',
 'ZNF554',
 'ZNF75A',
 'ZNF322',
 'FOXF1A',
 'BDP1',
 'NFE2L1',
 'RBPSUH-RS3',
 'ZIC3',
 'ERF',
 'SOX13',
 'NR4A2',
 'ZFP57',
 'ZFHX3',
 'NR1H',
 'BATF3',
 'TCFAP2B',
 'NKX3-2',
 'NFATC1',
 'POU3F1',
 'KLF6',
 'NPAS4',
 'TBX4',
 'AP3',
 'IRX6',
 'SOX7',
 'PRRXL1',
 'ZFP82',
 'ZNF418',
 'CR936877.3',
 'HERPUD1',
 'HOXA9',
 'TRP53',
 'ZBTB47',
 'YY1',
 'FXR',
 'ZFP691',
 'MLXIP',
 'HOXC8',
 'DUX4L2',
 'TCFCP2L1',
 'CREB',
 'MYPOP',
 'BCL11B',
 'MSC',
 'FOXI3',
 'MEF2D',
 'RARG',
 'USF',
 'FOXD4L3',
 'FOXD4',
 'RFX5',
 'TRP63',
 'POU4F1',
 'ZFP524',
 'AHRR',
 'HOXD8',
 'ARID3C',
 'PTF1A',
 'SMARCC2',
 'LBX2',
 'ESR1',
 'AIRE',
 'ETV3',
 'RORB',
 'ZNF165',
 'GTF3C2',
 'DLX2',
 'IKZF3',
 'KLF4',
 'NANOG',
 'NR2F2',
 'SIX6',
 'TEAD3',
 'CART1',
 'BSX',
 'NHLH2',
 'TP53',
 'EN2',
 'HOXA10',
 'GFI1',
 'ZNF490',
 'POU4F2',
 'MBTPS2',
 'STAT1',
 'AR',
 'C11ORF9',
 'HOXD11',
 'CR812478.2',
 'NR3C1',
 'SALL4',
 'CEBPA',
 'DMRTC2',
 'NKX3-1',
 'HOMEZ',
 'SP3',
 'CHD2',
 'DMRTA1',
 'FOXA3',
 'ZNF263',
 'Q8VHG7_MOUSE',
 'GTF2I',
 'MYF6',
 'RHOX8',
 'SREBF2',
 'TCFAP4',
 'JUND',
 'ZBTB14',
 'ENSG00000224558',
 'THRA',
 'PR',
 'NP_001076596.1',
 'SIX4',
 'NR5A2',
 'FOSL2',
 'TBX19',
 'NFIB',
 'AL662834.13',
 'RXRA',
 'EHF',
 'STAT5',
 'HF1H3B',
 'HOXA1',
 'CXXC1',
 'BRF1',
 'FOX',
 'MEF2A',
 'OTX',
 'TFAP2',
 'USF1',
 'NR1I3',
 'HOXD3',
 'NKX2-6',
 'FOXS1',
 'MZF1',
 'CREB3L4',
 'ZNF232',
 'FEV',
 'ZNF35',
 'ENSG00000234550',
 'HES2',
 'PRDM5',
 'ARID3B',
 'NP_083278.1',
 'HOXD9',
 'RBPJ',
 'NKX2.1',
 'STAT',
 'SOX8',
 'NANOGP1',
 'RFX3',
 'RELB',
 'TGIF2',
 'ARHGEF12',
 'TGIF2LX',
 'ZNF219',
 'CREBZF',
 'DUX4',
 'FOXD4L5',
 'ESR2',
 'BHLHE40',
 'HAND2',
 'MYB',
 'NFAT',
 'ZIC1',
 'ZNF708',
 'HMGA2',
 'PAX3',
 'PRDM14',
 'NKX2-2',
 'TBX10',
 'ZNF449',
 'LHX1',
 'GATA',
 'BBX',
 'CR388219.4',
 'HES7',
 'TEAD1',
 'BACH2',
 'ONECUT2',
 'SMAD3',
 'FOXI2',
 'ZFP369',
 'DMBX1',
 'NF1',
 'CTCFL',
 'BHLHB3',
 'ENSG00000234254',
 'ELF5',
 'ID3',
 'NP_032300.2',
 'OBOX3',
 'SMAD1',
 'STAT6',
 'SCX',
 'THAP1',
 'CEBP',
 'HES5',
 'IRF',
 'FOSL1',
 'HMGA1-RS1',
 'TCFAP2C',
 'SREBP2',
 'FOXK1',
 'GSC2',
 'ZNF143',
 'ESRRA',
 'HDAC2',
 'GCM1',
 'POU1F1',
 'FEZF1',
 'IRX3',
 'FOXB2',
 'BMAL1',
 'POLR3A',
 'FOSB',
 'LYL1',
 'EGR2',
 'SNAI3',
 'TCFAP2E',
 'HEYL',
 'ZFP219',
 'RFX2',
 'NR0B1',
 'SOX18',
 'TFAP2B',
 'WT1',
 'NR6A1',
 'CUX2',
 'HOXB6',
 'FOXD4L6',
 'SEF1',
 'ZNF281',
 'DLX5',
 'SP7',
 'AL844853.8',
 'PROX1',
 'DMRT1',
 'E2F7',
 'EGR',
 'NPAS1',
 'EMX1',
 'KLF10',
 'PAX4',
 'BARX2',
 'BPTF',
 'CCNT2',
 'MECOM',
 'ZNF435',
 'GM5454',
 'ATOH1',
 'ZNF549',
 'MBD2',
 'KLF3',
 'SOX6',
 'HOXC9',
 'NEUROG1',
 'VENTX',
 'HOXA11',
 'MYF5',
 'ZBTB1',
 'FOXK2',
 'AL773544.1',
 'PRRX2',
 'NEUROG3',
 'NFYC',
 'PRDM4',
 'EBF3',
 'NEUROD1',
 'PAX2',
 'AL592170.2',
 'HNF1B',
 'SMAD2',
 'TCFL5',
 'ESRRG',
 'YBX1',
 'ZNF335',
 'TBX15',
 'ZBTB6',
 'EN1',
 'TOPORS',
 'LHX5',
 'ZKSCAN3',
 'CEBPG',
 'EBF1',
 'MAZ',
 'DOBOX4',
 'TBX2',
 'ZNF148',
 'ZNF582',
 'SOX9',
 'TWIST2',
 'BHLHE23',
 'PBX2',
 'TCF7L1',
 'CR933878.8',
 'TFCP2L1',
 'AL662824.5',
 'DMRT2',
 'DMC1',
 'POU3F2',
 'RORA',
 'ZSCAN16',
 'NEUROD6',
 'FOXP4',
 'PAX7',
 'AC002126.6',
 'CR753803.1',
 'ZNF547',
 'TFDP3',
 'ZBTB42',
 'WRNIP1',
 'NFATC2',
 'TBET',
 'HOXB5',
 'GATA3',
 'OBOX6',
 'DUX',
 'SIM2',
 'MECP2',
 'SRY',
 'E2F4',
 'ZNF41',
 'PRDM16',
 'PBX3',
 'REST',
 'GLIS1',
 'P63',
 'ZNF324',
 'ENSG00000235187',
 'HIF1A',
 'PPARG',
 'BRCA1',
 'NFATC4',
 'POU5F1B',
 'NR1H5',
 'MBD1',
 'RAX',
 'NRL',
 'FOXB1',
 'TCF7L2',
 'SPI1',
 'CT476828.2',
 'IRF1',
 'NR3C2',
 'RUNX3',
 'ZNF589',
 'TGIF1',
 'SIM1',
 'MXI1',
 'PPARA',
 'SIRT6',
 'ZBTB49',
 'ELK1',
 'ZBTB17',
 'HINFP1',
 'ETV7',
 'ARNTL2',
 'DLX1',
 'MEOX1',
 'VSX1',
 'FOXC2',
 'ZNF680',
 'TR4',
 'STAT3',
 'GATA2',
 'MITF',
 'DPRX',
 'NR2F1',
 'NRF1',
 'ZNF18',
 'CUX1',
 'HOXB8',
 'KLF1',
 'CR388229.2',
 'NFIX',
 'TCFEC',
 'DMRTA2',
 'ELK3',
 'IRF9',
 'HIC2',
 'MGA',
 'NR2E1',
 'SP8',
 'TCF4',
 'TGIF2LY',
 'HIVEP2',
 'BCLAF1',
 'FEZF2',
 'OLIG2',
 'ENSG00000233794',
 'POU6F2',
 'RXRG',
 'CDX',
 'HNF1',
 'ATF2',
 'E4F1',
 'AL662828.6',
 'NEUROG2',
 'GLIS3',
 'IRF6',
 'SP1',
 'ZFP3',
 'MYEF2',
 'ZNF423',
 'KLF9',
 'FOXJ2',
 'ZFP238',
 'NR2C2',
 'RHOXF2',
 'POU2F3',
 'ID1',
 'STAT4',
 'MAF',
 'HMX1',
 'NKX6-2',
 'ZFP410',
 'POU3F4',
 'GTF2A',
 'DMRT3',
 'EBF',
 'NR2C1',
 'NFKB',
 'MAFF',
 'ZKSCAN4',
 'PIT1',
 'AL662830.5',
 'KLF7',
 'KLF2',
 'CEBPD',
 'GCM',
 'HLX',
 'ZBTB7A',
 'SRF',
 'IRX2',
 'HBP1',
 'FOXI1',
 'NR1H4',
 'ZBTB48',
 'ZNF563',
 'ONECUT3',
 'HIVEP1',
 'GSC',
 'SOX',
 'VEZF1',
 'NKX2-3',
 'TBR1',
 'OCT4',
 'GATA4',
 'ISL2',
 'LHX2',
 'FOXO4',
 'FRA2',
 'HOXB2',
 'SREBF',
 'BRN1',
 'HOXD4',
 'ZNF320',
 'IRC900814',
 'HSF2',
 'ELF4',
 'IKZF1',
 'BHLHB2',
 'NP_032283.3',
 'BARHL2',
 'PAX8',
 'CLOCK',
 'FOXC1',
 'SOX2',
 'AMYB',
 'AFP',
 'EBOX',
 'ZFP281',
 'ARNT2',
 'ATF1',
 'HSFY1',
 'HLF',
 'NPAS',
 'EMX2',
 'HOXA6',
 'ESX1',
 'POU6F1',
 'E2F1',
 'ATF4',
 'ENSG00000227522',
 'SCXB',
 'DBX1',
 'YBX2',
 'SPDEF',
 'SP9',
 'ERG',
 'ZNF329',
 'RUNX2',
 'peak_id',
 'ZNF394',
 'GSX1',
 'MEOX2',
 'TCF23',
 'KLF5',
 'FOXL2',
 'OSR2',
 'FOXM1',
 'OLIG1',
 'SP100',
 'ZFY1',
 'ZNF354A',
 'PHF21A',
 'RHOX11',
 'ZSCAN4',
 'TBX18',
 'GCM2',
 'NFYB',
 'ARX',
 'ATF6B',
 'DMRT6',
 'NRF2',
 'ZNF524',
 'ZBTB7C',
 'ZFP161',
 'POLR2A',
 'ZFP809',
 'RAD21',
 'NFKB1',
 'ZNF76',
 'CEBPB',
 'OTX1',
 'TEF',
 'IRF5',
 'GLI1',
 'MSX1',
 'PAX6',
 'TCF21',
 'NPAS2',
 'SCXA',
 'ASCL1',
 'HOXC6',
 'OLIG3',
 'LMO2',
 'TFAP4',
 'HMX3',
 'PHOX2A',
 'ZNF683',
 'PROP1',
 'CACD',
 'BRF2',
 'ZIC4',
 'AL845464.3',
 'ETV6',
 'ITGB2',
 'TCFAP2D',
 'EWSR1',
 'YY2',
 'ZNF382',
 'FOXH1',
 'SETDB1',
 'GSX2',
 'MEF2C',
 ...}

In [18]:
len(tf_names)

1096

In [19]:
#Only leaving the TFs that are in base GRN file
filtered_grn = filtered_grn[
    filtered_grn['source'].isin(tf_names) & filtered_grn['target'].isin(tf_names)
]

In [20]:
filtered_grn

,Unnamed: 0,source,target,coef_mean,coef_abs,p,-logp
407,407,FLI1,AIRE,-0.000041,0.000041,4.177123e-04,3.505783
409,409,NR3C1,AIRE,-0.000066,0.000066,1.378691e-04,4.009011
412,412,MEF2C,AIRE,0.000210,0.000210,1.073489e-17,19.000296
413,413,HNF4A,AIRE,0.000028,0.000028,1.485380e-02,1.898947
414,414,MAFK,AIRE,-0.000120,0.000120,1.176911e-09,9.486157
...,...,...,...,...,...,...,...
11695,11695,CREB3L3,ZNF75D,-0.001215,0.001215,3.426221e-06,5.700494
11696,11696,NR3C1,ZNF75D,0.021992,0.021992,2.876696e-09,9.044132
11697,11697,GRHL2,ZNF75D,0.027043,0.027043,1.228759e-12,12.944024
11698,11698,HNF4A,ZNF75D,0.001636,0.001636,7.424884e-06,5.343114
11700,11700,CREB5,ZNF75D,0.004429,0.004429,6.604977e-06,5.397084

In [21]:
# Sort by absolute coefficient descending
filtered_grn = filtered_grn.sort_values(by='coef_abs', ascending=False).reset_index(drop=True)

In [22]:
filtered_grn

     Unnamed: 0  source  target  coef_mean  coef_abs             p      -logp
0          4002   NPAS3    GLI2   0.100969  0.100969  2.192116e-17  18.637751
1          4142  BCL11A   GRHL2   0.076907  0.076907  6.840731e-18  19.233417
2           979   NR3C1  BCL11A   0.063920  0.063920  5.491807e-18  19.351081
3          5272  BCL11A    KLF8   0.047923  0.047923  7.217016e-16  16.846550
4          8377   NR3C1  PKNOX2   0.045080  0.045080  6.646620e-19  20.400821
..          ...     ...     ...        ...       ...           ...        ...
468         948   RUNX1   BARX2   0.000034  0.000034  1.424456e-02   1.917615
469        7362  TFAP2B  NKX3-1   0.000033  0.000033  1.873670e-02   1.795393
470       10518   HNF4A    TFEB  -0.000033  0.000033  2.127717e-02   1.738051
471        8255   NR0B1     PGR  -0.000029  0.000029  1.928049e-02   1.782491
472         413   HNF4A    AIRE   0.000028  0.000028  1.485380e-02   1.898947

[473 rows x 7 columns]

In [23]:
#Create Graph and run Leiden in 10 iterations, each time reducing the last 10% of rows
stepwise_results = []
step_size = math.ceil(len(filtered_grn) * 0.1)

for i in range(10):
    current_df = filtered_grn.iloc[:len(filtered_grn) - i * step_size].copy()
    step_label = f"{100 - i * 10}pct"

    # Build igraph and run Leiden
    edges = list(zip(current_df['source'], current_df['target']))
    weights = current_df['coef_abs'].tolist()
    ig_graph = ig.Graph.TupleList(edges, directed=True)
    ig_graph.es["weight"] = weights
    seed = 50
    partition = leidenalg.find_partition(
        ig_graph,
        leidenalg.RBConfigurationVertexPartition,
        weights=weights,
        seed=seed
    )
    
    # Build NetworkX DiGraph for connected components
    
    G_nx = nx.DiGraph()
    for _, row in current_df.iterrows():
        G_nx.add_edge(row['source'], row['target'], weight=row['coef_abs'])
    G_undirected = G_nx.to_undirected()
    connected_components = list(nx.connected_components(G_undirected))

    
    tf_communities = defaultdict(list)
    for comm_id, community in enumerate(partition):
        for v_index in community:
            tf = ig_graph.vs[v_index]["name"]
            if tf in tf_names:
                tf_communities[comm_id].append(tf)

    tf_community_list = []
    for comm_id, tf_list in tf_communities.items():
        for tf in tf_list:
            tf_community_list.append({"community": comm_id, "tf": tf})

    tf_community_df = pd.DataFrame(tf_community_list)
    tf_comm_path = f"tf_communities_step_{step_label}.csv"
    tf_community_df.to_csv(tf_comm_path, index=False)

    # Finding the edges of a graph which is the TF-TF interaction, assigning names and weight (based on abs_coeff),
    #Lastly checking if TFs are a part of community and if they are of the same community. 
    
    #This is the dictionary created in previous step
    tf_to_community = {tf: comm for comm, tfs in tf_communities.items() for tf in tfs}
    edges_in_community = []

    for edge in ig_graph.es:
        source = ig_graph.vs[edge.source]["name"]
        target = ig_graph.vs[edge.target]["name"]
        weight = edge["weight"]
        if source in tf_to_community and target in tf_to_community:
            if tf_to_community[source] == tf_to_community[target]:
                edges_in_community.append({
                    "community": tf_to_community[source],
                    "source": source,
                    "target": target,
                    "weight": weight
                })

    tf_edge_df = pd.DataFrame(edges_in_community)
    tf_edge_path = f"tf_community_edges_step_{step_label}.csv"
    tf_edge_df.to_csv(tf_edge_path, index=False)

    # Plotting, Partition is a community
    # plot_path = f"/home/giorgi_sokhadze/ml_new_data/plots/plot_step_{step_label}.png"
    # layout = ig_graph.layout("fr")
    # ig.plot(
    #     partition,
    #     layout=layout,
    #     target=plot_path,
    #     vertex_size=10,
    #     bbox=(800, 800),
    #     margin=20,
    #     vertex_label=None
    # )

    # Summary saving
    stepwise_results.append({
        "step": step_label,
        "n_edges": len(current_df),
        "n_leiden_communities": len(partition),
        "tf_counts_per_community": {k: len(v) for k, v in tf_communities.items()},
        "tf_communities_file": tf_comm_path,
        "tf_community_edges_file": tf_edge_path,
        "n_connected_components": len(connected_components),
        # "plot": plot_path
    })

In [24]:
# Final DataFrame
summary_df = pd.DataFrame(stepwise_results)
summary_df.to_csv("tf_tf_grn_summary.csv", index=False)
print("DONE")

DONE